[project]
name = "lambda"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.1",
    "opensearch-py>=3.0.0",
    "requests-aws4auth>=1.3.1",
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
    "tenacity>=9.1.2",
]
